name: Generate Snake

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate snake
        uses: Platane/snk@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: dist/snake.svg

      - name: Upload to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: snake.svg
          path: dist/snake.svg
