name: Generate Snake

on:
  schedule: # Schedule it to run at specific intervals
    - cron: "0 0 * * *" # Runs at every day at midnight
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4 # Node.js 20 güncellemesi

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: eneseldes
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Upload snake
        uses: actions/upload-artifact@v4 # Node.js 20 güncellemesi
        with:
          name: snake
          path: dist
